language: python
python:
  - "3.5"
  - "3.6"

notifications:
  email: false

install:
  - sudo apt-get install clustalo
  - python -m pip install coveralls codecov
  - python -m pip install .

script:
  - export PYTEST_ADDOPTS="--pylint"
  - python setup.py test

after_success:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then coveralls; fi
