language: python
python:
  - "3.5"
  - "3.6"

notifications:
  email: false

install:
  - python -m pip install coveralls codecov
  - python -m pip install -e .

script:
  - export PYTEST_ADDOPTS="--pylint"
  - python setup.py test
