language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -e .

script:
  - python setup.py test

after_success:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then coveralls; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then codecov; fi
