# https://github.com/coala/coala-quickstart/blob/master/.ci/appveyor.yml
environment:
  matrix:
    - PYTHON: "C:\\Python38-x64" # security : end-of-life 2024-10
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python310-x64" # bugfix : end-of-life 2026-10
      PYTHON_VERSION: "3.10"
      PYTHON_ARCH: "64"
    # https://devguide.python.org/versions/#versions

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade setuptools pip wheel"
  - "python -m pip install --upgrade pytest coveralls codecov"
  - "python setup.py install"
  - ps: (new-object net.webclient).DownloadFile('https://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_i86win32.exe', 'C:\\projects\\thoraxe\\muscle.exe')

build: false

test_script:
  - "python setup.py test"
  - "codecov.exe"
