# https://github.com/coala/coala-quickstart/blob/master/.ci/appveyor.yml
environment:
  matrix:
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

install:
  - ps: (new-object net.webclient).DownloadFile('http://www.clustal.org/omega/clustalo-1.2.4-Ubuntu-x86_64', 'C:\\projects\\thoraxe\\clustalo')
  - ps: ls
  - bash -c "ls"
  - bash -c "pwd"
  - ps: pwd
  - bash -c "sudo chmod a+x /c/projects/thoraxe/clustalo"
  - ps: ICACLS "clustalo" /grant:r "users:(RX)" /C
  - ps: ls
  - bash -c "ls -l"
  - bash -c "/c/projects/thoraxe/clustalo -h"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - "python -m pip install --upgrade setuptools pip"
  - "python -m pip install coveralls codecov"
  - "python -m pip install numpy" # is needed to install scikit-bio
  - "python -m pip install -e ."


build: false

test_script:
  - "python setup.py test "
  - "codecov.exe"
